# Generated by Django 6.0.6 on 2026-06-28 01:37

import bank_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_alter_userprofile_refund_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=bank_app.models.CloudinaryField(blank=True, null=True, upload_to='profile_pics/', verbose_name='profile_pic'),
        ),
    ]
